name: OpenVPNServ2

on:
  push:
  pull_request:

jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Latest Mono & MSBuild
        run: |
          sudo apt update
          sudo apt install -y gnupg ca-certificates

          sudo gpg --homedir /tmp --no-default-keyring \
            --keyring /usr/share/keyrings/mono-official-archive-keyring.gpg \
            --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

          echo \
            "deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/ubuntu stable-focal main" | \
            sudo tee /etc/apt/sources.list.d/mono-official-stable.list

          # Update and install Mono & MSBuild
          sudo apt update
          sudo apt install -y mono-devel msbuild

      - name: Build
        run: ./build.sh

  win:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [ "Any CPU", "x86", "x64" ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Solution
        run: msbuild OpenVpnService.sln /p:Configuration=Release "/p:Platform=${{ matrix.platform }}"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenVpnService-${{ matrix.platform }}
          path: |
                bin/Release/**
                bin/x86/Release/**
                bin/x64/Release/**

